name: Compilar SM64 NDS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Corregir y Construir entorno de compilación (Docker)
        run: |
          # Modificar el Dockerfile original en caliente para asegurar que actualice los repositorios
          sed -i 's/RUN apt update/RUN apt-get update \&\& apt-get upgrade -y/g' Dockerfile
          sed -i 's/RUN apt -y install/RUN apt-get -y --no-install-recommends install/g' Dockerfile
          
          # Construir la imagen local
          docker build -t sm64 .

      - name: Compilar juego usando Docker
        run: |
          docker run --rm --mount type=bind,source="$(pwd)",destination=/sm64 sm64 make VERSION=us -j4

      - name: Guardar archivo ejecutable (.NDS)
        uses: actions/upload-artifact@v4
        with:
          name: super-mario-64-nds
          path: build/us/*.nds
